In [6]:
#masking

import torch

attn_weights = torch.tensor([[0.1921, 0.1646, 0.1652, 0.1550, 0.1721, 0.1510],
        [0.2041, 0.1659, 0.1662, 0.1496, 0.1665, 0.1477],
        [0.2036, 0.1659, 0.1662, 0.1498, 0.1664, 0.1480],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.1661, 0.1564],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.1585],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]])

mask = torch.triu(torch.ones(6,6), diagonal=1)
mask

masked = attn_weights.masked_fill(mask.bool(),-torch.inf)
print(masked)

attn_weights_normalized = torch.softmax(masked/2**0.5,dim=-1)
attn_weights_normalized


tensor([[0.1921,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.2041, 0.1659,   -inf,   -inf,   -inf,   -inf],
        [0.2036, 0.1659, 0.1662,   -inf,   -inf,   -inf],
        [0.1869, 0.1667, 0.1668, 0.1571,   -inf,   -inf],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658,   -inf],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]])


tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5068, 0.4932, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3393, 0.3303, 0.3304, 0.0000, 0.0000, 0.0000],
        [0.2531, 0.2495, 0.2495, 0.2478, 0.0000, 0.0000],
        [0.2021, 0.1998, 0.1998, 0.1987, 0.1996, 0.0000],
        [0.1698, 0.1666, 0.1666, 0.1652, 0.1666, 0.1650]])

In [7]:
#using torch.nn.Dropout

torch.manual_seed(123)
dropout = torch.nn.Dropout(0.5)
example = torch.ones(6,6)
dropout(example)

tensor([[2., 2., 2., 2., 2., 2.],
        [0., 2., 0., 0., 0., 0.],
        [0., 0., 2., 0., 2., 0.],
        [2., 2., 0., 0., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [0., 2., 0., 0., 0., 0.]])