In [17]:
#A very simple example of a sentence that has been encoded in a 3x3 higher dimensional space

import torch

inputs = torch.tensor(
    [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [5]:
# alignment between the token "journey" and the token "Your"
# this "alignment" is a scalar, a projection. 
# again, just physics.
# this is called an attention score

attn_score = torch.dot(inputs[0],inputs[1])

attn_score


tensor(0.9544)

In [12]:
# attension scores for the second token w.r.t to all other tokens in the sentence

query = inputs[1]

attn_scores = torch.empty(inputs.shape[0])

for i,x_i in enumerate(inputs):
    attn_scores[i] = torch.dot(x_i, inputs[i])

attn_scores

tensor([0.9995, 1.4950, 1.4570, 0.4937, 0.6654, 0.9450])

In [13]:
# attension scores of each token w.r.t to all other tokens

attn_scores = inputs@inputs.T

attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [14]:
# Now this part isn't physics.
# It has been found that model training is much more efficiency and higher quality with
# normalized scores. These normalized scores are called weights.
# Attention Weights.
# There are easy and naive ways to normalize. We will use softmax.
# Moreso because because we will later use a very cool property of softmax wherein we can obtain
# probababilities. But let's not get ahead of ourselves right now.

attn_weights = torch.softmax(attn_scores, dim=-1)

attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [15]:
# Now that we know the relative alignment of each input token with respect to ever other input token
# we can compute the context vectors which are the vector composition of the attention weights with each 
# token, and then vector added together

context_vectors = attn_weights @ inputs

context_vectors

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])